const PLAYERS=['p1','p2','p3'];
const DEPTH=3;
const same=(a,b)=>a.colour===b.colour&&a.value===b.value;
const matches=(a,b)=>a.colour===b.colour||a.value===b.value;
const isSkip=c=>c.value==='Skip';
function clone(s){return{p1:s.p1.map(x=>({...x})),p2:s.p2.map(x=>({...x})),p3:s.p3.map(x=>({...x})),top_card:{...s.top_card},deck:s.deck.map(x=>({...x})),discards:s.discards.map(x=>({...x}))}}
function valid(s,p){return s[p].filter(c=>matches(c,s.top_card))}
function apply(s,p,m){const n=clone(s);let skipped=null;if(m===null){if(!n.deck.length&&n.discards.length){n.deck=n.discards;n.discards=[];for(let i=n.deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[n.deck[i],n.deck[j]]=[n.deck[j],n.deck[i]]}}if(n.deck.length)n[p].push(n.deck.pop())}else{const i=n[p].findIndex(c=>same(c,m));if(i<0)throw new Error('AI chose a card not in its hand');n[p].splice(i,1);n.discards.push(n.top_card);n.top_card={...m};if(isSkip(m))skipped=PLAYERS[(PLAYERS.indexOf(p)+1)%3]}return[n,skipped]}
function evaluate(s,p,kind){const o=PLAYERS.filter(x=>x!==p);const own=s[p].length,opp=(s[o[0]].length+s[o[1]].length)/2,sk=s[p].filter(isSkip).length;return kind==='defensive'?50-6*own+2*opp+4*sk:50-5*own+3*opp+2*sk}
function terminal(s,p,d){for(const q of PLAYERS)if(s[q].length===0)return q===p?1000+d:-1000-d;return null}
function search(s,d,p,cp,sk,kind,alpha,beta,ctx){if(++ctx.nodes>=ctx.maxNodes||performance.now()>=ctx.deadline)return[evaluate(s,p,kind),null,true];const t=terminal(s,p,d);if(t!==null)return[t,null,false];if(d<=0)return[evaluate(s,p,kind),null,false];if(sk.has(cp)){const ns=new Set(sk);ns.delete(cp);return search(s,d,p,PLAYERS[(PLAYERS.indexOf(cp)+1)%3],ns,kind,alpha,beta,ctx)}const actions=valid(s,cp);const choices=actions.length?actions:[null];const maximizing=cp===p;let best=maximizing?-Infinity:Infinity,bestMove=choices[0];const next=PLAYERS[(PLAYERS.indexOf(cp)+1)%3];for(const m of choices){const[n,sp]=apply(s,cp,m);const[v,,cut]=search(n,d-1,p,next,sp?new Set([sp]):new Set(),kind,alpha,beta,ctx);if(maximizing?v>best:v<best){best=v;bestMove=m}if(maximizing)alpha=Math.max(alpha,best);else beta=Math.min(beta,best);if(beta<=alpha||cut)break}return[best,bestMove,false]}
self.onmessage=e=>{try{const {state,player}=e.data;const kind=player==='p1'?'defensive':'offensive';const ctx={nodes:0,maxNodes:20000,deadline:performance.now()+300};const [value,move]=search(state,DEPTH,player,player,new Set(),kind,-Infinity,Infinity,ctx);postMessage({ok:true,move,value,nodes:ctx.nodes})}catch(err){postMessage({ok:false,error:err.message||String(err)})}};