const COLOURS=['Red','Blue','Green','Yellow'];const NUMBERS=[0,1,2,3,4,5,6,7,8,9];const PLAYERS=['p1','p2','p3'];const NAMES={p1:'P1 (Minimax Defensive)',p2:'P2 (Expectimax Offensive)',p3:'P3 (Human)'};const DEPTH=3;const $=id=>document.getElementById(id);let state,current='p1',skipped=new Set(),turn=0,winner=null,history=[],busy=false,worker=null;
function card(c,v){return{colour:c,value:v}}function same(a,b){return a.colour===b.colour&&a.value===b.value}function matches(a,b){return a.colour===b.colour||a.value===b.value}function isSkip(c){return c.value==='Skip'}
function deckGenerator(){const d=[];for(const c of COLOURS){for(const n of NUMBERS)d.push(card(c,n));d.push(card(c,'Skip'))}for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function newState(){const d=deckGenerator(),s={p1:[],p2:[],p3:[],top_card:d.pop(),deck:d,discards:[]};for(const p of PLAYERS)for(let i=0;i<5;i++)s[p].push(d.pop());while(isSkip(s.top_card)){s.deck.unshift(s.top_card);s.top_card=s.deck.pop()}return s}
function clone(s){return{p1:s.p1.map(x=>({...x})),p2:s.p2.map(x=>({...x})),p3:s.p3.map(x=>({...x})),top_card:{...s.top_card},deck:s.deck.map(x=>({...x})),discards:s.discards.map(x=>({...x}))}}
function validMoves(s,p){return s[p].filter(c=>matches(c,s.top_card))}
function applyMove(s,p,move){const n=clone(s);let sp=null;if(move===null){if(!n.deck.length&&n.discards.length){n.deck=n.discards;n.discards=[];for(let i=n.deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[n.deck[i],n.deck[j]]=[n.deck[j],n.deck[i]]}}if(n.deck.length)n[p].push(n.deck.pop())}else{const i=n[p].findIndex(c=>same(c,move));if(i<0)throw new Error('Invalid AI move');n[p].splice(i,1);n.discards.push(n.top_card);n.top_card={...move};if(isSkip(move))sp=PLAYERS[(PLAYERS.indexOf(p)+1)%3]}return[n,sp]}
function label(c){return c?`${c.colour} ${c.value}`:'Draw'}function log(msg){history.unshift(msg);$('log').innerHTML=history.slice(0,12).map(x=>`<div class="log">${x}</div>`).join('')}
function render(){for(const p of PLAYERS){$(p).classList.toggle('active',p===current);$(p+'count').textContent=state[p].length}$('turn').textContent=turn;$('deck').textContent=state.deck.length;$('discards').textContent=state.discards.length;$('active').textContent=current.toUpperCase();const t=$('topCard');t.className='card '+state.top_card.colour.toLowerCase();t.querySelector('span').textContent=state.top_card.colour;t.querySelector('strong').textContent=state.top_card.value;const hand=$('hand');hand.innerHTML='';state.p3.forEach((c,i)=>{const b=document.createElement('button');b.className='card '+c.colour.toLowerCase();b.innerHTML=`<span>${c.colour}</span><strong>${c.value}</strong>`;const ok=matches(c,state.top_card)&&current==='p3'&&!busy&&!winner;b.disabled=!ok;if(!ok)b.classList.add('invalid');b.onclick=()=>humanPlay(i);hand.appendChild(b)})}
function setMsg(x){$('message').textContent=x}
function showAI(p){$('aiInfo').innerHTML=p==='p1'?'<div class="decision"><span>Algorithm</span><b>Minimax + Alpha-Beta</b></div><div class="decision"><span>Heuristic</span><b>Defensive</b></div><div class="decision"><span>Depth</span><b>3</b></div>':'<div class="decision"><span>Algorithm</span><b>Expectimax</b></div><div class="decision"><span>Heuristic</span><b>Offensive</b></div><div class="decision"><span>Depth</span><b>3</b></div>'}
function runMove(p,move){const[n,sp]=applyMove(state,p,move);state=n;turn++;log(`${NAMES[p]} ${move===null?'draws a card':'plays '+label(move)+(sp?' · SKIP':'')}`);if(sp)skipped.add(sp);if(!state[p].length){winner=p;busy=false;setMsg(`${NAMES[p]} wins!`);render();return}current=PLAYERS[(PLAYERS.indexOf(p)+1)%3];if(skipped.has(current)){skipped.delete(current);turn++;log(`${NAMES[current]} is SKIPPED`);current=PLAYERS[(PLAYERS.indexOf(current)+1)%3]}continueTurn()}
function continueTurn(){render();if(winner)return;if(current==='p3'){busy=false;setMsg(validMoves(state,'p3').length?'Your turn — play a matching card.':'No valid move — draw a card.');return}setMsg(`${NAMES[current]} is thinking…`);setTimeout(aiTurn,100)}
function aiTurn(){if(winner||busy)return;busy=true;render();const p=current;showAI(p);if(worker)worker.terminate();worker=new Worker('ai-worker.js');const started=performance.now();let settled=false;const finish=(move,nodes,error)=>{if(settled)return;settled=true;worker.terminate();worker=null;busy=false;if(error){log(`${NAMES[p]} search error: ${error}`);const fallback=validMoves(state,p)[0]??null;setMsg(`${NAMES[p]} used a safe fallback move.`);runMove(p,fallback);return}log(`${NAMES[p]} searched ${nodes.toLocaleString()} nodes in ${Math.round(performance.now()-started)}ms`);runMove(p,move??null)};worker.onmessage=e=>e.data.ok?finish(e.data.move,e.data.nodes):finish(null,0,e.data.error);worker.onerror=()=>finish(null,0,'AI worker failed to load');worker.postMessage({state:clone(state),player:p});setTimeout(()=>finish(null,0,'AI search timed out'),1200)}
function drawHuman(){if(current!=='p3'||busy||winner)return;if(validMoves(state,'p3').length){setMsg('You have a valid move — you must play it.');return}runMove('p3',null)}function humanPlay(i){if(current!=='p3'||busy||winner)return;const c=state.p3[i];if(matches(c,state.top_card))runMove('p3',c)}$('drawHuman').onclick=drawHuman;$('draw').onclick=drawHuman;$('newGame').onclick=()=>start();function start(){if(worker)worker.terminate();worker=null;state=newState();current='p1';skipped=new Set();turn=0;winner=null;history=[];busy=false;$('aiInfo').textContent='P1 will calculate a defensive Minimax move.';setMsg('P1 is thinking…');render();setTimeout(aiTurn,300)}start();
