const COLOURS=['Red','Blue','Green','Yellow'];const NUMBERS=[0,1,2,3,4,5,6,7,8,9];const PLAYERS=['p1','p2','p3'];const NAMES={p1:'P1 (Minimax Defensive)',p2:'P2 (Expectimax Offensive)',p3:'P3 (Human)'};const DEPTH=3;
const $=id=>document.getElementById(id);let state,current='p1',skipped=new Set(),turn=0,winner=null,history=[],busy=false;
function card(c,v){return{colour:c,value:v}}function key(c){return c.colour+'|'+c.value}function same(a,b){return a.colour===b.colour&&a.value===b.value}function matches(a,b){return a.colour===b.colour||a.value===b.value}function isSkip(c){return c.value==='Skip'}
function deckGenerator(){const d=[];for(const c of COLOURS){for(const n of NUMBERS)d.push(card(c,n));d.push(card(c,'Skip'))}for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function newState(){const d=deckGenerator();const s={p1:[],p2:[],p3:[],top_card:d.pop(),deck:d,discards:[]};for(const p of PLAYERS)for(let i=0;i<5;i++)s[p].push(d.pop());let attempts=0;while(isSkip(s.top_card)&&s.deck.length&&attempts<10){s.deck.unshift(s.top_card);s.top_card=s.deck.pop();attempts++}return s}
function clone(s){return{p1:s.p1.map(x=>({...x})),p2:s.p2.map(x=>({...x})),p3:s.p3.map(x=>({...x})),top_card:{...s.top_card},deck:s.deck.map(x=>({...x})),discards:s.discards.map(x=>({...x}))}}
function validMoves(s,p){return s[p].filter(c=>matches(c,s.top_card))}
function applyMove(s,p,move){const n=clone(s);let skip=null;if(move===null){if(!n.deck.length&&n.discards.length){n.deck=n.discards;n.discards=[];for(let i=n.deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[n.deck[i],n.deck[j]]=[n.deck[j],n.deck[i]]}}if(n.deck.length)n[p].push(n.deck.pop())}else{const i=n[p].findIndex(c=>same(c,move));if(i>=0)n[p].splice(i,1);n.discards.push(n.top_card);n.top_card={...move};if(isSkip(move))skip=PLAYERS[(PLAYERS.indexOf(p)+1)%3]}return[n,skip]}
function evaluate(s,p,strategy){const opp=PLAYERS.filter(x=>x!==p);const cai=s[p].length,copp=(s[opp[0]].length+s[opp[1]].length)/2,skipCount=s[p].filter(isSkip).length;return strategy==='defensive'?50-6*cai+2*copp+4*skipCount:50-5*cai+3*copp+2*skipCount}
function terminal(s,p,depth){for(const q of PLAYERS)if(s[q].length===0)return q===p?1000+depth:-1000-depth;return null}
function minimax(s,depth,p,cp,skip,alpha=-Infinity,beta=Infinity){const win=terminal(s,p,depth);if(win!==null)return[win,null];if(depth===0)return[evaluate(s,p,'defensive'),null];if(skip.has(cp)){const ns=new Set(skip);ns.delete(cp);return minimax(s,depth,p,PLAYERS[(PLAYERS.indexOf(cp)+1)%3],ns,alpha,beta)}const actions=validMoves(s,cp),choices=actions.length?actions:[null],max=cp===p;let best=max?-Infinity:Infinity,bestMove=choices[0];const next=PLAYERS[(PLAYERS.indexOf(cp)+1)%3];for(const move of choices){const[n,sp]=applyMove(s,cp,move);const[v]=minimax(n,depth-1,p,next,sp?new Set([sp]):new Set(),alpha,beta);if(max){if(v>best){best=v;bestMove=move}alpha=Math.max(alpha,best)}else{if(v<best){best=v;bestMove=move}beta=Math.min(beta,best)}if(beta<=alpha)break}return[best,bestMove]}
function chanceValue(s,cp,p,next,skip,depth){if(!s.deck.length)return evaluate(s,p,'offensive');const counts=new Map();for(const c of s.deck){const k=key(c);counts.set(k,(counts.get(k)||0)+1)}let total=0;for(const [k,count] of counts){const [colour,value]=k.split('|');const draw=card(colour,value==='Skip'?'Skip':Number(value));const n=clone(s);n[cp].push(draw);const i=n.deck.findIndex(c=>same(c,draw));if(i>=0)n.deck.splice(i,1);const[v]=expectimax(n,depth-1,p,next,skip);total+=(count/s.deck.length)*v}return total}
function expectimax(s,depth,p,cp,skip){const win=terminal(s,p,depth);if(win!==null)return[win,null];if(depth===0)return[evaluate(s,p,'offensive'),null];if(skip.has(cp)){const ns=new Set(skip);ns.delete(cp);return expectimax(s,depth,p,PLAYERS[(PLAYERS.indexOf(cp)+1)%3],ns)}const valid=validMoves(s,cp),next=PLAYERS[(PLAYERS.indexOf(cp)+1)%3];if(cp===p){let best=-Infinity,bestMove=null;for(const move of valid){const[n,sp]=applyMove(s,cp,move);const[v]=expectimax(n,depth-1,p,next,sp?new Set([sp]):new Set());if(v>best){best=v;bestMove=move}}if(!valid.length){if(s.deck.length)return[chanceValue(s,cp,p,next,new Set(),depth),null];return[evaluate(s,p,'offensive'),null]}return[best,bestMove]}const actions=valid.length?valid:[null];let total=0;for(const move of actions){const[n,sp]=applyMove(s,cp,move);const[v]=expectimax(n,depth-1,p,next,sp?new Set([sp]):new Set());total+=v}return[total/actions.length,null]}
function label(c){return c?`${c.colour} ${c.value}`:'Draw'}function log(msg){history.unshift(msg);$('log').innerHTML=history.slice(0,12).map(x=>`<div class="log">${x}</div>`).join('')}
function render(){for(const p of PLAYERS){$(p).classList.toggle('active',p===current);$(p+'count').textContent=state[p].length}$('turn').textContent=turn;$('deck').textContent=state.deck.length;$('discards').textContent=state.discards.length;$('active').textContent=current.toUpperCase();const t=$('topCard');t.className='card '+state.top_card.colour.toLowerCase();t.querySelector('span').textContent=state.top_card.colour;t.querySelector('strong').textContent=state.top_card.value;const hand=$('hand');hand.innerHTML='';state.p3.forEach((c,i)=>{const b=document.createElement('button');b.className='card '+c.colour.toLowerCase();b.innerHTML=`<span>${c.colour}</span><strong>${c.value}</strong>`;const ok=matches(c,state.top_card)&&current==='p3'&&!busy&&!winner;b.disabled=!ok;if(!ok)b.classList.add('invalid');b.onclick=()=>humanPlay(i);hand.appendChild(b)})}
function setMsg(x){$('message').textContent=x}
$('drawHuman').onclick=()=>{if(current!=='p3'||busy||winner)return;if(validMoves(state,'p3').length){setMsg('You have a valid move — you must play it.');return}runMove('p3',null)};$('draw').onclick=()=>$('drawHuman').click();$('newGame').onclick=()=>start();
function humanPlay(i){if(current!=='p3'||busy||winner)return;const c=state.p3[i];if(!matches(c,state.top_card))return;runMove('p3',c)}
function continueTurn(){render();if(winner)return;if(current==='p3'){setMsg(validMoves(state,'p3').length?'Your turn — play a matching card.':'No valid move — draw a card.')}else{setMsg(`${NAMES[current]} is thinking…`);setTimeout(aiTurn,450)}}
function runMove(p,move){const[n,sp]=applyMove(state,p,move);state=n;turn++;if(move===null)log(`${NAMES[p]} draws a card`);else log(`${NAMES[p]} plays ${label(move)}${sp?' · SKIP':''}`);if(sp)skipped.add(sp);if(!state[p].length){winner=p;setMsg(`${NAMES[p]} wins!`);render();return}current=PLAYERS[(PLAYERS.indexOf(p)+1)%3];if(skipped.has(current)){skipped.delete(current);turn++;log(`${NAMES[current]} is SKIPPED`);current=PLAYERS[(PLAYERS.indexOf(current)+1)%3]}continueTurn()}
function aiTurn(){if(winner)return;busy=true;render();const p=current;if(skipped.has(p)){skipped.delete(p);busy=false;turn++;log(`${NAMES[p]} is SKIPPED`);current=PLAYERS[(PLAYERS.indexOf(p)+1)%3];continueTurn();return}if(p==='p1')$('aiInfo').innerHTML='<div class="decision"><span>Algorithm</span><b>Minimax + Alpha-Beta</b></div><div class="decision"><span>Heuristic</span><b>Defensive</b></div><div class="decision"><span>Depth</span><b>3</b></div>';else $('aiInfo').innerHTML='<div class="decision"><span>Algorithm</span><b>Expectimax</b></div><div class="decision"><span>Heuristic</span><b>Offensive</b></div><div class="decision"><span>Chance nodes</span><b>Deck probabilities</b></div>';let move;if(p==='p1')move=minimax(state,DEPTH,'p1','p1',new Set(skipped))[1];else move=expectimax(state,DEPTH,'p2','p2',new Set(skipped))[1];busy=false;runMove(p,move===undefined?null:move)}
function start(){state=newState();current='p1';skipped=new Set();turn=0;winner=null;history=[];busy=false;$('aiInfo').textContent='P1 will calculate a defensive Minimax move.';setMsg('P1 is thinking…');render();setTimeout(aiTurn,500)}start();
